### ISSUE TITLE
[Atom 1.17.0] [Fix] Missing commands when right clicking project folder or specific file

### ISSUE THREAD

**Issue by dtsdev** [MariusRumpf/copy-filename#6]
After recent Atom upgrade to 1.17.0 the context menu commands disappeared. To fix this:
1. Open `.atom\packages\copy-filename\menus\copy-filename.json` 
2. In lines 19 and 28 change `.tree-view.full-menu` to `.tool-panel.tree-view`.

Restart Atom, done.

**Comment by MariusRumpf** [comment]
Thx, please check out v1.1.0. Is it working for you?

**Comment by dtsdev** [comment]
@MariusRumpf thank you! Works like a charm now.
